language: java
jdk:
 - oraclejdk8

cache:
 directories:
 - "$HOME/.cache"

deploy:
 provider: script
 script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
 skip_cleanup: true
 on:
   branches:
     only:
       - master
       - stable